services:
  # nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  # php
  app:
    build:
      dockerfile: ./php/Dockerfile

  # mysql
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: intoy
      MYSQL_USER: user
      MYSQL_PASSWORD: intoy
      MYSQL_DATABASE: docker-php

volumes:
  mysqldata: